// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVIsQNEOOj0ZwJvJ7lcwhqIEOIsb1LTjc',
    appId: '1:725505399516:web:be880563f7130e08bef219',
    messagingSenderId: '725505399516',
    projectId: 'svcam-dev',
    authDomain: 'svcam-dev.firebaseapp.com',
    storageBucket: 'svcam-dev.firebasestorage.app',
    measurementId: 'G-ZBN4DFL30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhGH0C9qf2Wi4AX43Vau33qzJ5QJExVk',
    appId: '1:725505399516:android:66d5d4102787ea8abef219',
    messagingSenderId: '725505399516',
    projectId: 'svcam-dev',
    storageBucket: 'svcam-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPi_q_81b9PgawocDyc2qKZzjRBesQuJg',
    appId: '1:725505399516:ios:80aaba8dd3a45378bef219',
    messagingSenderId: '725505399516',
    projectId: 'svcam-dev',
    storageBucket: 'svcam-dev.firebasestorage.app',
    iosBundleId: 'com.example.svcamV001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPi_q_81b9PgawocDyc2qKZzjRBesQuJg',
    appId: '1:725505399516:ios:80aaba8dd3a45378bef219',
    messagingSenderId: '725505399516',
    projectId: 'svcam-dev',
    storageBucket: 'svcam-dev.firebasestorage.app',
    iosBundleId: 'com.example.svcamV001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVIsQNEOOj0ZwJvJ7lcwhqIEOIsb1LTjc',
    appId: '1:725505399516:web:ee58998c5f0f0e1abef219',
    messagingSenderId: '725505399516',
    projectId: 'svcam-dev',
    authDomain: 'svcam-dev.firebaseapp.com',
    storageBucket: 'svcam-dev.firebasestorage.app',
    measurementId: 'G-KMHYJJ3MYM',
  );

}